--IPLS | MISSING MAP PIECES
Citizen.CreateThread(function()
	OnEnterMp(1)
	RequestIpl("FIBlobbyfake")
	RequestIpl("DT1_03_Gr_Closed")
	RequestIpl("v_tunnel_hole")
	RequestIpl("TrevorsMP")
	RequestIpl("TrevorsTrailer")
	RequestIpl("farm")
	RequestIpl("farmint")
	RequestIpl("farmint_cap")
	RequestIpl("farm_props")
	RequestIpl("CS1_02_cf_offmission")
end)